Django/pythonProject/insta/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from config.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("", index),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

Django/pythonProject/insta/posts/urls.py
from django.urls import path

from posts.views import feeds

urlpatterns = [
    path("feeds/", feeds),
]

Django/pythonProject/insta/users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup

urlpatterns = [
    path("login/", login_view),
    path("logout/", logout_view),
    path("signup/", signup),
]

Django/pythonProject/insta/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class PostImage(models.Model):
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey("users.User", verbose_name="작성자", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)

Django/pythonProject/insta/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    profile_image = models.ImageField(
        "프로필 이미지", upload_to="user/profile", blank=True)
    short_description = models.TextField("소개글", blank=True)

Django/pythonProject/insta/posts/forms.py
from django import forms
from posts.models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

Django/pythonProject/insta/users/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        widget=forms.TextInput(attrs={"placeholder":"사용자명 (3자리 이상)"},
        ),
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호 (4자리 이상)"},
        ),
    )

class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    profile_image = forms.ImageField()
    short_description = forms.CharField()

Django/pythonProject/insta/config/views.py
from django.shortcuts import render, redirect

def index(request):
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")
    else:
        return redirect("/users/login/")

Django/pythonProject/insta/posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post
from posts.forms import CommentForm
# Create your views here.
def feeds(request):
    if not request.user.is_authenticated:
        return redirect("/users/login/")

    user = request.user
    if not user.is_authenticated:
        return redirect("users:login")

    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
    }
    return render(request, "posts/feeds.html", context)

Django/pythonProject/insta/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from users.forms import LoginForm, SignupForm
from users.models import User
# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")

    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect("/posts/feeds/")
            else:
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다.")

        context = {"form": form}
        return render(request, "users/login.html", context)
    else:
        form = LoginForm()
        context = {"form": form}
        return render(request, "users/login.html", context)

def logout_view(request):
    logout(request)
    return redirect("/users/login")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password1 = form.cleaned_data["password1"]
            password2 = form.cleaned_data["password2"]
            profile_image = form.cleaned_data["profile_image"]
            short_description = form.cleaned_data["short_description"]

            if password1 != password2:
                form.add_error("password2", "비번 다름")

            if User.objects.filter(username=username).exists():
                form.add_error("username", "아이디 존재")

            if form.errors:
                context = {"form" : form}
                return render(request, "users/signup.html", context)
            else:
                user = User.objects.create_user(
                    username = username,
                    password= password1,
                    profile_image = profile_image,
                    short_description = short_description,
                )
                login(request, user)
                return redirect("/posts/feeds/")
    else:
        form = SignupForm()
        context = {"form":form}
        return render(request, "users/signup.html", context)

Django/pythonProject/insta/templates/_base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Titigram</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block base_content %}{% endblock %}
</body>
</html>

Django/pythonProject/insta/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

Django/pythonProject/insta/templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
{% endblock %}

Django/pythonProject/insta/templates/base_profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
    <div class="info">
        <!-- 프로필 이미지 영역 -->
        {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}">
        {% endif %}

        <!-- 사용자 정보 영역 -->
        <div class="info-texts">
            <h1>{{ user.username }}</h1>
            <div class="counts">
                <dl>
                    <dt>Posts</dt>
                    <dd>
                        <a href="{% url 'users:profile' user_id=user.id %}">{{ user.post_set.count }}</a>
                    </dd>
                    <dt>Followers</dt>
                    <dd>
                        <a href="{% url 'users:followers' user_id=user.id %}">{{ user.followers.count }}</a>
                    </dd>
                    <dt>Following</dt>
                    <dd>
                        <a href="{% url 'users:following' user_id=user.id %}">{{ user.following.count }}</a>
                    </dd>
                </dl>
            </div>
            <p>{{ user.short_description }}</p>
        </div>
    </div>
    {% block bottom_data %}{% endblock %}
</div>
{% endblock %}

Django/pythonProject/insta/templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link href="{% static 'splide/splide.css' %}" rel="stylesheet">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock %}

Django/pythonProject/insta/templates/nav.html
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Titigram</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">포스트 등록</a>
    <a href="{% url 'users:logout' %}">로그아웃</a>
</nav>

Django/pythonProject/insta/templates/posts/feeds.html
{% extends 'base.html' %}
{% block content %}
<nav>
    <h1>Titigram</h1>
</nav>
<div id="feeds" class="post-container">
    {% for post in posts %}
        <article class="post">
            <header class="post-header">
                {% if post.user.profile_image %}
                    <img src="{{post.user.profile_image.url}}">
                {% endif %}
                <span>{{ post.user.username }}</span>
            </header>


            <div class="post-images splide">
                <div class="splide__track">
                    <ul class="splide__list">
                        {% for image in post.postimage_set.all %}
                            {% if image.photo %}
                            <li class="splide__slide">
                                <img src="{{ image.photo.url}}">
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="post-content">
                {{post.content|linebreaksbr}}
            </div>

            <div class="post-buttons">
                <button>Likes(0)</button>
                <span>Comments(0)</span>
            </div>

            <div class="post-comments">
                <ul>
                    {% for comment in post.comment_set.all %}
                        <li>
                            <span>{{comment.user.username}}</span>
                            <span>{{comment.content}}</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <small>{{post.created}}</small>
            <div class="post-comment-create">
                <input type="text" placeholder="댓글 달기">
                <button type="submit">계시</button>
            </div>
        </article>
    {% endfor %}
</div>
<script>
    const elms = document.getElementsByClassName('splide')
    for (let i = 0; i< elms.length; i++){
        new Splide(elms[i]).mount();
    }
</script>
{% endblock %}

Django/pythonProject/insta/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>로그인</title>
</head>
<body>
<div id="login">
    <form method="POST">
        <h1>Titigram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-login">로그인</button>
        <a href="/users/signup/">회원가입 페이지로 이동</a>
    </form>
</div>
</body>
</html>
{% endblock %}

Django/pythonProject/insta/templates/users/signup.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>회원가입</title>
</head>
<body>
<div id="signup">
    <form method="POST" , enctype="multipart/form-data">
        <h1>Titigram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-signup">가입</button>
        <a href="/users/login/">로그인 페이지로 이동</a>
    </form>
</div>
</body>
</html>
{% endblock %}